name: Deploy to GitHub Pages

on:
  push:
    branches:
      - development
    paths:
      - 'apps/web/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test --watchAll=false

      - name: Build Project
        run: yarn build

      - name: Configure Git Identity
        run: |
          git config --global user.email "auto-deploy@quick-relay.com"
          git config --global user.name "Quick Relay CI"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh-pages -d build -r https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git